spring:
  application:
    name: backend

  datasource:
#    url: jdbc:postgresql://localhost:5432/reizen
    url: ${DB_URL}
    username: ${DB_U}
    password: ${DB_P}
    driver-class: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
